import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import StateContextProvider from "@/components/StateContextProvider";
import { ThemeProvider } from "@/components/themeprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <StateContextProvider>
        <body className={inter.className}>
          {/* <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > */}
            <div className="layout">
              <header>
                <NavBar />
              </header>
              <main className="main-container">{children}</main>
              <footer>
                <Footer />
              </footer>
            </div>
          {/* </ThemeProvider> */}
        </body>
      </StateContextProvider>
    </html>
  );
}
